"""add plan interval fields

Revision ID: b77180f58749
Revises: 46db3e8d3429
Create Date: 2026-01-26 11:46:12.939508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77180f58749'
down_revision: Union[str, Sequence[str], None] = '46db3e8d3429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('interval_count', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('interval_unit', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'interval_unit')
    op.drop_column('plans', 'interval_count')
    # ### end Alembic commands ###
